export const projects = [
    {
      id: "project1",
      img: "https://raw.githubusercontent.com/johnatticus/friends-in-training/main/public/images/signUp.png",
      link: "https://afternoon-island-74965.herokuapp.com/login",
      title: "Friends in Training",
      description: "Friends in Training modal. Made with js and mysql db.",
    },
    {
      id: "project2",
      img: "https://user-images.githubusercontent.com/99369137/163577743-4a735fde-5b2c-4311-bde2-5be432e952c9.png",
      link: "https://guzzemetti.github.io/economic-eats/",
      title: "Economic Eats",
      description: "Economic Eats modal",
    },
    {
      id: "project3",
      img: "https://raw.githubusercontent.com/johnatticus/react-portfolio-v2/main/src/img/team-profile-generator.png",
      link: "https://github.com/johnatticus/Team-Profile-Generator",
      title: "Team Profile Generator",
      description: "this is example change me later",
    },
    {
      id: "project4",
      img: "https://raw.githubusercontent.com/johnatticus/Quiz-Game/main/assets/images/quizscreenshot.png",
      link: "https://johnatticus.github.io/Quiz-Game/",
      title: "Gonzo Quiz",
      description: "this is example change me later",
    },
    {
      id: "project5",
      img: "https://raw.githubusercontent.com/johnatticus/Password_Generator/main/pwgeneratorscreenshot.png",
      link: "https://johnatticus.github.io/Password_Generator/",
      title: "Password Generator",
      description: "this is example change me later",
    },
    {
      id: "project6",
      img: "https://raw.githubusercontent.com/johnatticus/Social-Network-API/main/assets/images/screenshot.png",
      link: "https://github.com/johnatticus/Social-Network-API",
      title: "Social Network API",
      description: "this is example change me later",
    },
    {
      id: "project7",
      img: "https://raw.githubusercontent.com/johnatticus/private-practice-v2/main/client/src/assets/screenshot.png?token=GHSAT0AAAAAABZRZ7RTE2R5Z5KQR4ILMT4OY7Y3BQQ",
      link: "https://johnatticus.github.io/Password_Generator/",
      title: "Private Practice",
      description: "this is example change me later",
    },
    {
      id: "project8",
      img: "https://raw.githubusercontent.com/johnatticus/MVC-Tech-Blog/main/assets/images/screenshot.png",
      link: "https://github.com/johnatticus/MVC-Tech-Blog",
      title: "MVC Tech Blog",
      description: "this is example change me later",
    },
  ];